### PR TITLE
Run Enscale NodeJS application via supervisor

### PR DESCRIPTION
**Pull request by darius-luca-tech**
article

### CODE REVIEW

**Review by rauladorean — CHANGES_REQUESTED** [review]
``sudo /etc/init.d/cartridge stop`` is no longer relevant.

**Comment by darius-luca-tech** [comment]
removed 'Set up a cron to make this the default at server boot' part from the article

**Comment by darius-luca-tech** [comment]
pushed something new.

Per our last discussion regarding this article, we agreed upon on showing the customer how to deploy a NodeJS app within Enscale...so here it is :)

**Review by rauladorean — APPROVED** [review]
Looks OK

**Pull request merged**
