### PR TITLE
article

### PR DESCRIPTION
**Pull request by darius-luca-tech**

### CODE REVIEW

**Review by rauladorean — CHANGES_REQUESTED** [review]
Needs new screenshots due to address changes

**Comment by darius-luca-tech** [comment]
Changed the screenshot(last one from gate.j => sshgateway.io)

**Comment by darius-luca-tech** [comment]
https://blog.layershift.com/generating-jelastic-ssh-keys-puttygen/

**Review by rauladorean — APPROVED** [review]
Ok

**Pull request merged**
